const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Dictionary,
		C3.Plugins.progressbar,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetInstanceVar,
		C3.Plugins.Particles.Acts.RotateClockwise,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Particles.Cnds.CompareInstanceVar,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Exps.Rate,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.progressbar.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.progressbar.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.progressbar.Acts.SetSize,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.Text.Exps.UID,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Particles.Acts.MoveForward,
		C3.Plugins.Particles.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetWrapping,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetFontFace
	];
};
self.C3_JsPropNameTable = [
	{amika_ey: 0},
	{mag_ey: 0},
	{stato: 0},
	{dirauto: 0},
	{dirauto_spd: 0},
	{speed: 0},
	{amika: 0},
	{mag: 0},
	{dir: 0},
	{stato_mov: 0},
	{spd: 0},
	{color: 0},
	{altro_stato1: 0},
	{amika_an: 0},
	{mag_an: 0},
	{astbg: 0},
	{Tiledast1: 0},
	{sfondo: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{imgpnt: 0},
	{Particles1: 0},
	{Text: 0},
	{attualetxt: 0},
	{dialoghi: 0},
	{bar1: 0},
	{bar2: 0},
	{tab1: 0},
	{Pin: 0},
	{minitab1: 0},
	{dic_dialoghi: 0},
	{life_pbar: 0},
	{img_bar: 0},
	{gear: 0},
	{astronave: 0},
	{altro_scroll: 0},
	{altro_scroll_time: 0},
	{altro_scroll_spd: 0},
	{ScrollTo: 0},
	{camera: 0},
	{comet1: 0},
	{M45_monitor_169_nologo: 0},
	{velautoschermprinc: 0},
	{rotazionevel: 0},
	{stellapiùmenoscale: 0},
	{instsizepiùmeno: 0},
	{nebulosaspwnstelleBO: 0},
	{nebulosa_stellacentraSTR: 0},
	{nebulosa: 0},
	{stella: 0},
	{zelev: 0},
	{star1: 0},
	{nuvola_fumo: 0},
	{anime: 0},
	{txt_tab: 0},
	{tab: 0},
	{personaggi: 0},
	{t_eyes: 0},
	{AUTOLAYER1: 0},
	{animation1BO: 0},
	{x: 0},
	{y: 0},
	{scale: 0},
	{quantity: 0},
	{angrange: 0},
	{statoGioco: 0},
	{veltesti: 0},
	{statoanime: 0},
	{fine_firstdialogo: 0},
	{funzione: 0},
	{stringa: 0},
	{text: 0},
	{tme: 0},
	{layout_time: 0}
];

self.InstanceType = {
	amika_ey: class extends self.ISpriteInstance {},
	mag_ey: class extends self.ISpriteInstance {},
	amika: class extends self.ISpriteInstance {},
	mag: class extends self.ISpriteInstance {},
	amika_an: class extends self.ISpriteInstance {},
	mag_an: class extends self.ISpriteInstance {},
	astbg: class extends self.ISpriteInstance {},
	Tiledast1: class extends self.ITiledBackgroundInstance {},
	sfondo: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Particles1: class extends self.IParticlesInstance {},
	Text: class extends self.ITextInstance {},
	dialoghi: class extends self.ITextInstance {},
	bar1: class extends self.ITextInstance {},
	bar2: class extends self.ITextInstance {},
	tab1: class extends self.ISpriteInstance {},
	minitab1: class extends self.ISpriteInstance {},
	dic_dialoghi: class extends self.IDictionaryInstance {},
	life_pbar: class extends self.IProgressBarInstance {},
	img_bar: class extends self.ISpriteInstance {},
	gear: class extends self.ISpriteInstance {},
	astronave: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	comet1: class extends self.ISpriteInstance {},
	M45_monitor_169_nologo: class extends self.ISpriteInstance {},
	nebulosa: class extends self.ISpriteInstance {},
	stella: class extends self.ISpriteInstance {},
	star1: class extends self.ISpriteInstance {},
	nuvola_fumo: class extends self.ISpriteInstance {},
	anime: class extends self.ISpriteInstance {},
	txt_tab: class extends self.ITextInstance {},
	tab: class extends self.ISpriteInstance {},
	personaggi: class extends self.ISpriteInstance {},
	t_eyes: class extends self.ISpriteInstance {},
	AUTOLAYER1: class extends self.ISpriteInstance {}
}